# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StreakViewer/uidesign/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(748, 817)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 748, 19))
        self.menubar.setObjectName("menubar")
        self.menuDo = QtWidgets.QMenu(self.menubar)
        self.menuDo.setObjectName("menuDo")
        self.menuNodes = QtWidgets.QMenu(self.menuDo)
        self.menuNodes.setObjectName("menuNodes")
        self.menuMeasure = QtWidgets.QMenu(self.menubar)
        self.menuMeasure.setObjectName("menuMeasure")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setFloating(False)
        self.dockWidget.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetWidget = QtWidgets.QWidget()
        self.dockWidgetWidget.setObjectName("dockWidgetWidget")
        self.layoutCalcTreeWidget = QtWidgets.QGridLayout(self.dockWidgetWidget)
        self.layoutCalcTreeWidget.setContentsMargins(0, 0, 0, 0)
        self.layoutCalcTreeWidget.setObjectName("layoutCalcTreeWidget")
        self.dockWidget.setWidget(self.dockWidgetWidget)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.dockWidget_2 = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_2.sizePolicy().hasHeightForWidth())
        self.dockWidget_2.setSizePolicy(sizePolicy)
        self.dockWidget_2.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget_2.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.widgetwidget = QtWidgets.QWidget()
        self.widgetwidget.setAutoFillBackground(True)
        self.widgetwidget.setObjectName("widgetwidget")
        self.layoutImageInfo = QtWidgets.QGridLayout(self.widgetwidget)
        self.layoutImageInfo.setContentsMargins(0, 0, 0, 0)
        self.layoutImageInfo.setObjectName("layoutImageInfo")
        self.dockWidget_2.setWidget(self.widgetwidget)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_2)
        self.actionRecalc = QtWidgets.QAction(MainWindow)
        self.actionRecalc.setObjectName("actionRecalc")
        self.actionAddSumNode = QtWidgets.QAction(MainWindow)
        self.actionAddSumNode.setObjectName("actionAddSumNode")
        self.actionAdd_File = QtWidgets.QAction(MainWindow)
        self.actionAdd_File.setObjectName("actionAdd_File")
        self.actionAddPolarizationNode = QtWidgets.QAction(MainWindow)
        self.actionAddPolarizationNode.setObjectName("actionAddPolarizationNode")
        self.actionAutoLevel = QtWidgets.QAction(MainWindow)
        self.actionAutoLevel.setObjectName("actionAutoLevel")
        self.actionSleep = QtWidgets.QAction(MainWindow)
        self.actionSleep.setObjectName("actionSleep")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionGet_Background = QtWidgets.QAction(MainWindow)
        self.actionGet_Background.setObjectName("actionGet_Background")
        self.actionImages = QtWidgets.QAction(MainWindow)
        self.actionImages.setCheckable(True)
        self.actionImages.setChecked(True)
        self.actionImages.setObjectName("actionImages")
        self.actionImage_Info = QtWidgets.QAction(MainWindow)
        self.actionImage_Info.setCheckable(True)
        self.actionImage_Info.setChecked(True)
        self.actionImage_Info.setObjectName("actionImage_Info")
        self.actionStartMeasurement = QtWidgets.QAction(MainWindow)
        self.actionStartMeasurement.setEnabled(False)
        self.actionStartMeasurement.setObjectName("actionStartMeasurement")
        self.dockWidget_2.raise_()
        self.dockWidget.raise_()
        self.menuNodes.addAction(self.actionAddSumNode)
        self.menuNodes.addAction(self.actionAddPolarizationNode)
        self.menuDo.addAction(self.actionRecalc)
        self.menuDo.addAction(self.actionAdd_File)
        self.menuDo.addAction(self.menuNodes.menuAction())
        self.menuDo.addAction(self.actionAutoLevel)
        self.menuDo.addAction(self.actionSleep)
        self.menuDo.addAction(self.actionSave)
        self.menuMeasure.addAction(self.actionGet_Background)
        self.menuMeasure.addAction(self.actionStartMeasurement)
        self.menuView.addAction(self.actionImages)
        self.menuView.addAction(self.actionImage_Info)
        self.menubar.addAction(self.menuDo.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuMeasure.menuAction())

        self.retranslateUi(MainWindow)
        self.actionImages.toggled['bool'].connect(self.dockWidget.setVisible)
        self.actionImage_Info.toggled['bool'].connect(self.dockWidget_2.setVisible)
        self.dockWidget.visibilityChanged['bool'].connect(self.actionImages.setChecked)
        self.dockWidget_2.visibilityChanged['bool'].connect(self.actionImage_Info.setChecked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuDo.setTitle(_translate("MainWindow", "Image"))
        self.menuNodes.setTitle(_translate("MainWindow", "Add Nodes"))
        self.menuMeasure.setTitle(_translate("MainWindow", "Measurement"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "Images"))
        self.dockWidget_2.setWindowTitle(_translate("MainWindow", "Image Info"))
        self.actionRecalc.setText(_translate("MainWindow", "Recalc"))
        self.actionAddSumNode.setText(_translate("MainWindow", "Sum"))
        self.actionAdd_File.setText(_translate("MainWindow", "Add File"))
        self.actionAddPolarizationNode.setText(_translate("MainWindow", "Polarization"))
        self.actionAutoLevel.setText(_translate("MainWindow", "Auto Level"))
        self.actionSleep.setText(_translate("MainWindow", "Sleep"))
        self.actionSave.setText(_translate("MainWindow", "Save Current Image"))
        self.actionGet_Background.setText(_translate("MainWindow", "Get Background"))
        self.actionImages.setText(_translate("MainWindow", "Images"))
        self.actionImage_Info.setText(_translate("MainWindow", "Image Info"))
        self.actionStartMeasurement.setText(_translate("MainWindow", "Start"))

